#!/bin/bash

#
auto_generated_file="auto_generated_ghld_commands.sh"
auto_generated_folder="_output"
python_script_file="main_ghdl.py"


#Removes $auto_generated_file if this one exist
[ -e $auto_generated_file ] && rm $auto_generated_file

#Removes $auto_generated_folder if this one exist
[ -d "../${auto_generated_folder}" ] && rm -r "../${auto_generated_folder}"

#Gets the path where the bash file has run
ghdlScriptsFolder=$(dirname $(realpath $0))

#Pass an argument to the python script and then run it
python "${ghdlScriptsFolder}/${python_script_file}" $auto_generated_file


#Verifies if the $auto_generated_file was generated by python script
if [ -f $auto_generated_file ]; then

    #Keeps in memory the current location
    location_auto_generated_file=$(pwd)

    #Sets user file permissions (rwx)
	chmod 700 $auto_generated_file

    #Makes a directory for compiled files
    mkdir "../${auto_generated_folder}"

    #Moves to the generated directory
    cd "../${auto_generated_folder}"
    
    #Runs the bash script with the ghdl commands
    "${location_auto_generated_file}/${auto_generated_file}"

fi



